In [1]:
### Talk about Nimpy Functionality..

In [2]:
import numpy as np

In [5]:
list(range(5))    ### if you put the list inside a range it produce a data which is 0 to 5..

[0, 1, 2, 3, 4]

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
### Rnage function contain only a integer..not folat value..

In [11]:
list(np.arange(.4 , 10.4, 0.2))  ## Arange is alternative range function it will be able to take even a floating point number based on this ....it will be generate a data sets..

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [14]:
np.linspace(1,5 , 20) ## linspace is used to generate a data set whatever a number data set i would like to generate scale range or equal step size..

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [17]:
np.logspace(1,5 , 10 , base = 2)  ## it will be generate a data based on a logrithmic..

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))  ## it will generate a data 3 rows and 4 column..

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
arr = np.ones((3,4))

In [27]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr+5 ## it will be able to add each element 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [30]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [31]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [33]:
arr1 = np.eye(5)

In [34]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
import pandas as pd

In [37]:
pd.DataFrame(arr1)  ## using this it will be able to covert all arry in dataframe..

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [38]:
np.random.rand(2,3)

array([[0.80887178, 0.17254249, 0.40399473],
       [0.78732796, 0.656767  , 0.01988147]])

In [39]:
np.random.randn(2,3)

array([[-0.30766507, -0.01281871, -0.57869834],
       [-1.46685789,  1.80537973, -0.23841382]])

In [40]:
## Difference between rand and randn..
## Rand = this is give you dataset where its average or mean can be anything or standard deviation can be anything ..
## Randn = On a normal standard deviation it will be going to generate a data and standard npraml destribution simply means that mean equal to zero...and standard deviation equal to one..

In [42]:
arr2 = np.random.randint(1,5 , (3,4))

In [43]:
arr2

array([[1, 3, 4, 2],
       [3, 3, 1, 2],
       [4, 2, 4, 2]])

In [44]:
arr2.size

12

In [45]:
arr2.shape

(3, 4)

In [46]:
## How to change a shape 
arr2.reshape(6,2)

array([[1, 3],
       [4, 2],
       [3, 3],
       [1, 2],
       [4, 2],
       [4, 2]])

In [49]:
arr2.reshape(2,6)

array([[1, 3, 4, 2, 3, 3],
       [1, 2, 4, 2, 4, 2]])

In [50]:
arr2.reshape(4,3)

array([[1, 3, 4],
       [2, 3, 3],
       [1, 2, 4],
       [2, 4, 2]])

In [51]:
arr2.reshape(4,-1)

array([[1, 3, 4],
       [2, 3, 3],
       [1, 2, 4],
       [2, 4, 2]])

In [52]:
arr2.reshape(4,-133564758)

array([[1, 3, 4],
       [2, 3, 3],
       [1, 2, 4],
       [2, 4, 2]])

In [53]:
arr2.reshape(2,2,3)

array([[[1, 3, 4],
        [2, 3, 3]],

       [[1, 2, 4],
        [2, 4, 2]]])

In [54]:
arr1 = np.random.randint(1,10 , (5,6))

In [55]:
arr1

array([[7, 9, 4, 5, 8, 9],
       [7, 3, 6, 9, 8, 7],
       [6, 1, 9, 2, 9, 5],
       [4, 3, 4, 2, 2, 6],
       [8, 6, 7, 6, 9, 6]])

In [56]:
## filter the which is greater than 8
arr1 > 8

array([[False,  True, False, False, False,  True],
       [False, False, False,  True, False, False],
       [False, False,  True, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [57]:
arr1[arr1 >8]

array([9, 9, 9, 9, 9, 9])

In [58]:
arr1

array([[7, 9, 4, 5, 8, 9],
       [7, 3, 6, 9, 8, 7],
       [6, 1, 9, 2, 9, 5],
       [4, 3, 4, 2, 2, 6],
       [8, 6, 7, 6, 9, 6]])

In [59]:
## how will be able to extract the data set in rows and column..
arr1[0,[0,1]]

array([7, 9])

In [60]:
arr1[2:4 , [2,3]]

array([[9, 2],
       [4, 2]])

In [63]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [64]:
arr1

array([[2, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [65]:
arr2

array([[1, 1, 2],
       [2, 1, 1],
       [1, 1, 2]])

In [66]:
arr1+arr2

array([[3, 3, 3],
       [3, 2, 2],
       [3, 2, 3]])

In [67]:
arr1-arr2

array([[ 1,  1, -1],
       [-1,  0,  0],
       [ 1,  0, -1]])

In [68]:
arr1*arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [71]:
arr1    ## this is not a matrix wise multiplication ..it is index wise 

array([[2, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [72]:
arr2

array([[1, 1, 2],
       [2, 1, 1],
       [1, 1, 2]])

In [73]:
## how to matrix multiplication
arr1@arr2

array([[7, 5, 8],
       [4, 3, 5],
       [5, 4, 7]])

In [74]:
arr1/arr2

array([[2. , 2. , 0.5],
       [0.5, 1. , 1. ],
       [2. , 1. , 0.5]])

In [75]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [76]:
## Numpy - Broadcasting.

In [77]:
arr = np.zeros((3,4))

In [78]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [80]:
a = np.array([1,2,3,4])

In [81]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [84]:
## Create a array to perform a operation on row wise..
b = np.array([[3,4,5]])

In [87]:
arr1 = arr+b.T

In [88]:
b.T

array([[3],
       [4],
       [5]])

In [89]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [90]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [91]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [92]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [93]:
np.min(arr1)

3.0

In [94]:
np.max(arr1)

5.0